-- Migration: Create DeteClima tables and stored procedures
-- Applied on: 2026-05-25

-- 1. Create user_locations table for saved interest zones
CREATE TABLE IF NOT EXISTS public.user_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for security
ALTER TABLE public.user_locations ENABLE ROW LEVEL SECURITY;

-- Set user policies
CREATE POLICY "Allow users to read their own locations"
  ON public.user_locations FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Allow users to insert their own locations"
  ON public.user_locations FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to delete their own locations"
  ON public.user_locations FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- 2. Create weather_queries table to log weather request histories
CREATE TABLE IF NOT EXISTS public.weather_queries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lat DOUBLE PRECISION NOT NULL,
  lon DOUBLE PRECISION NOT NULL,
  location_name TEXT NOT NULL,
  data_json JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.weather_queries ENABLE ROW LEVEL SECURITY;

-- 3. Create chat_messages table to store chatbot conversation histories
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  weather_context TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

-- 4. Create predictions table for RandomForest Regressor prediction logging
CREATE TABLE IF NOT EXISTS public.predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lat DOUBLE PRECISION NOT NULL,
  lon DOUBLE PRECISION NOT NULL,
  predicted_data JSONB NOT NULL,
  metrics_json JSONB NOT NULL,
  model_version TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.predictions ENABLE ROW LEVEL SECURITY;


-- =========================================================================
-- STORED PROCEDURES / DATABASE FUNCTIONS
-- =========================================================================

-- Stored Procedure to save a weather query via RPC
CREATE OR REPLACE FUNCTION public.save_weather_query_sp(
  p_lat DOUBLE PRECISION,
  p_lon DOUBLE PRECISION,
  p_location_name TEXT,
  p_data_json JSONB
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER -- Runs with creator privileges to insert into weather_queries
AS $$
BEGIN
  INSERT INTO public.weather_queries (lat, lon, location_name, data_json)
  VALUES (p_lat, p_lon, p_location_name, p_data_json);
END;
$$;
